Feature/public snippet
Crunchy-Torch/coddy pull request #20
Opened 2017-09-09 13:38 UTC by DavidLevayer

* Allow snippet to be accessed without being logged in
* Refactor frontend template model: remove sidebar, add navbar

2017-09-09 14:32 UTC, Nexucis commented
je  résoudrerais les conflits ce soir, j'ai pas réussi là y a un truc qui a foiré dans mon merge local :/

2017-09-09 17:42 UTC, Nexucis commented
Alors après avoir bien vérifié avant merge et après merge que j'étais iso avec ce qui est proposé ici, il y a quelques petits soucis dans la navigation : 

1. Lorsqu'on se log, la page d'overview se charge effectivement, mais le composant de login reste. Cependant si je fais F5 après être loggé, la page overview est rechargé et les snippet apparaissent

2. Lorsqu'on est sur l'overview, quand on clique sur une snippet, l'url change effectivement mais la page n'est pas chargé pour afficher la snippet en question.

Sinon outre ces petits soucis, effectivement c'est plus sympa qu'avec le design précédent. Par contre je me suis demandé : 

1. est ce que ce serait pas mieux que le footer apparaisse tout le temps ? 
2. Si l'on souhaite faire une recherche avancée, ce sera dans une autre page ?
3. Tu ne souhaitais pas renommer les permissions ?

2017-09-09 17:44 UTC, Nexucis requested changes
il a quelques fixes à faire pour avoir une navigation fluide et ce sera top. Voir les commentaires fait sur la MR directement :)

2017-09-10 08:18 UTC, DavidLevayer commented
Effectivement, ça chie un peu. Plusieurs solutions possibles. Faut qu'on en discute.

2017-09-13 20:33 UTC, Nexucis approved these changes

2017-09-13 20:34 UTC, merged