Feature/add snippet
Crunchy-Torch/coddy pull request #24
Opened 2017-10-06 15:39 UTC by DavidLevayer

This pull request contains:
* Angular reactive form to create a new snippet
* Toast notification system
* Visual improvements

Coming soon (in another pull request):
* Animation
* Other visual improvements (homepage and navbar)
* Update and Delete a snippet
* Syntax coloring system for source code

2017-10-13 18:00 UTC, Nexucis requested changes
Y a un petit soucis concernant la gestion du token JWT. Il n'est pas passé pour les requêtes POST pour créer une snippet. Du coup j'ai un 401 Unauthorized

2017-10-14 13:10 UTC, DavidLevayer commented
Fix via les deux derniers commits

2017-10-14 13:49 UTC, DavidLevayer commented
Fix via les deux derniers commits.

⚠️  Un bug peut apparaître si tu as un token dans `localstorage.getItem('token');` 
c'est un bug legacy causé par un token résiduel : si c'est le cas : `localstorage.clear()` devrait résoudre le problème.

2017-10-14 20:23 UTC, Nexucis commented
tiens c'est bizarre ça, quand je créé une snippet, y a pas l’auteur qui est mis . Du coup on a une snippet sans auteur

2017-10-14 20:45 UTC, DavidLevayer commented
C'est parce que c'est là : https://github.com/Crunchy-Torch/coddy/pull/26

2017-10-14 20:50 UTC, Nexucis approved these changes

2017-10-14 20:54 UTC, merged