Migration From Jersey to Spring-MVC + Spring Security
Crunchy-Torch/coddy pull request #50
Opened 2018-05-10 13:52 UTC by Nexucis

## Description
* Create Security package where all security stuff will be done
* Complete revision of the permission
  * Use `@PreAuthorize` instead of `@RolesAllowed`
  * Rename and remove old permission by only two : ROLE_ADMIN and ROLE_USER
* Review Security permission checking using filter (used in WebSecurityConfig) and using bean (UserSecurityService and SnippetSecurityService used in @PreAuthorize annotation)
* Remove AppUtils (not usefull class in fact)
* Remove CorsConfig class and use `@CrossOrigin` annotation instead
* Made a test on snippet API
## Migration Mapping between Jersey classes and Spring classes
* All Mapper are replaced by a ControllerAdvice in the package exception.handler.impl
* `@RolesAllowed`  replaced by `@PreAuthorized`
* `@GET` / `@POST` ..etc + `@Path` + `@Consummes` + `@Produces` replaces by `@RequestMapping`

2018-05-11 15:01 UTC, DavidLevayer commented on README.md
> +##### CODDY_SECURITY_JWT_SESSION_TIMEOUT_MIN
J'aurais pas mis le `_MIN` à la fin... la précision dans la doc suffit non ?

2018-05-11 15:07 UTC, DavidLevayer commented on back/src/main/java/org/crunchytorch/coddy/application/exception/handler/impl/ExceptHandler.java
> +public class ExceptHandler implements IExceptionHandler<Exception> {
ExceptionHandler ou DefaultExceptionHandler ?

2018-05-11 15:08 UTC, DavidLevayer commented on back/src/main/java/org/crunchytorch/coddy/application/exception/handler/impl/NotAllowedHandler.java
> +public class NotAllowedHandler implements IExceptionHandler<HttpRequestMethodNotSupportedException> {
MethodNotAllowedHandler ?

2018-05-11 15:15 UTC, DavidLevayer commented on back/src/main/java/org/crunchytorch/coddy/security/filter/AuthorizationRequestFilter.java
> +        // if not we should throw an exception
throw exception or remove comment

2018-05-11 15:21 UTC, DavidLevayer commented on back/src/main/java/org/crunchytorch/coddy/snippet/api/Snippet.java
> +    public SnippetEntity create(@RequestBody SnippetEntity snippet) {
Être loggué pour pouvoir ajouter un snippet ?

2018-05-11 15:23 UTC, DavidLevayer commented on back/src/main/java/org/crunchytorch/coddy/snippet/api/Snippet.java
> +    public SnippetEntity create(@RequestBody SnippetEntity snippet) {
C'est fait je pense, j'ai du zapper me code...

2018-05-11 15:24 UTC, DavidLevayer commented on back/src/main/java/org/crunchytorch/coddy/user/api/User.java
> +    public JWTToken authentication(@RequestBody final Credential credential) {
renomme en `authenticate` ? Comme ça on garde des verbes partout pour les actions API

2018-05-11 15:29 UTC, DavidLevayer commented on back/src/main/java/org/crunchytorch/coddy/user/api/User.java
> +    @PreAuthorize("hasRole('" + Permission.ADMIN + "') or (hasRole('" + Permission.USER + "') and @userSecurityService.ownsAccount(#login))")
Remarque générale pour tout les `@PreAuthorize` : que penses-tu d'une méthode `isAllowed` (qui pourrait être issue d'une interface par ailleurs !) permettant de définir les règles d'accès ?

Parce que là, on a la moitié de la logique dans l'annotation (notamment pour l'accès aux administrateurs), et la moitié dans le `SecurityService` concerné. J'aurais bien vu la totalité de la logique au même endroit (simplicité + maintenabilité), à savoir dans le `SecurityService`.

Qu'en penses-tu ?

2018-05-11 15:32 UTC, DavidLevayer requested changes
Voir les commentaires de la PR

2018-05-11 16:41 UTC, Nexucis commented on back/src/main/java/org/crunchytorch/coddy/snippet/api/Snippet.java
> +    public SnippetEntity create(@RequestBody SnippetEntity snippet) {
c'est fait dans la classe WebSecurityConfig. C'est un peu brainFuck j'avoue parce qu'en regardant uniquement cette classe tu te dis effectivement faut pas être authentifier pour y accéder

2018-05-11 16:45 UTC, Nexucis commented on back/src/main/java/org/crunchytorch/coddy/user/api/User.java
> +    @PreAuthorize("hasRole('" + Permission.ADMIN + "') or (hasRole('" + Permission.USER + "') and @userSecurityService.ownsAccount(#login))")
Je ne pense pas que ce soit une bonne idée. La logique est effectivement splitté en deux parties parce que d'abord il y a une logique qui vérifie les roles (avec la méthode hasRole, et je ne sais pas comment on peut y avoir accès en dehors de cette annotation et c'est surtout ça qui m'embête) et ensuite y a la logique plus "business" qui va vérifier que la personne est le propriétaire de la ressource.

Ce sont deux vérifications différentes.

2018-05-11 16:51 UTC, Nexucis commented on back/src/main/java/org/crunchytorch/coddy/user/api/User.java
> +    @PreAuthorize("hasRole('" + Permission.ADMIN + "') or (hasRole('" + Permission.USER + "') and @userSecurityService.ownsAccount(#login))")
et je pense que ce sera pas forcément plus simple du fait qu'il faudra implémenter la logique qui prend plusieurs rôles en parametre + le "and" pour certains role. Tu vois ce que je veux dire ?

2018-05-11 16:52 UTC, Nexucis commented on back/src/main/java/org/crunchytorch/coddy/user/api/User.java
> +    @PreAuthorize("hasRole('" + Permission.ADMIN + "') or (hasRole('" + Permission.USER + "') and @userSecurityService.ownsAccount(#login))")
Et en terme de lisibilité je trouve que ça se lit plutôt bien tu trouve pas ?

2018-05-11 16:53 UTC, Nexucis commented on back/src/main/java/org/crunchytorch/coddy/application/exception/handler/impl/ExceptHandler.java
> +public class ExceptHandler implements IExceptionHandler<Exception> {
va pour DefaultExceptionHandler

2018-05-11 16:56 UTC, Nexucis commented on back/src/main/java/org/crunchytorch/coddy/user/api/User.java
> +    public JWTToken authentication(@RequestBody final Credential credential) {
effectivement me suis loupé là dessus

2018-05-11 16:59 UTC, Nexucis commented on README.md
> +##### CODDY_SECURITY_JWT_SESSION_TIMEOUT_MIN
bah c'est quand tu fais un env en bash et que t'as cette variable qui est affiché, tu sais direct c'est quoi le type de la variable (i.e. en minute)

2018-05-11 17:04 UTC, Nexucis commented on back/src/main/java/org/crunchytorch/coddy/application/exception/handler/impl/NotAllowedHandler.java
> +public class NotAllowedHandler implements IExceptionHandler<HttpRequestMethodNotSupportedException> {
ouais beaucoup mieux

2018-05-11 17:05 UTC, Nexucis commented on back/src/main/java/org/crunchytorch/coddy/security/filter/AuthorizationRequestFilter.java
> +        // if not we should throw an exception
j'ai throw une exception finalement. Visiblement la convention qui préfixe token par Bearer n'est pas si annodine que ça [ voir la définition du header Authorization](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Authorization)

2018-05-14 11:41 UTC, DavidLevayer commented on README.md
> +##### CODDY_SECURITY_JWT_SESSION_TIMEOUT_MIN
Comme tu veux, mais je maintiens mon point de vue : ça se fait pas...
Regarde : https://httpd.apache.org/docs/2.4/mod/core.html
Fait une recherche sur "timeout". L'unité n'est jamais présente dans le nom de la variable. Par contre elle y est dans le détail de la documentation.

2018-05-14 11:42 UTC, DavidLevayer commented on back/src/main/java/org/crunchytorch/coddy/security/filter/AuthorizationRequestFilter.java
> +        // if not we should throw an exception
ok

2018-05-14 11:42 UTC, DavidLevayer commented on back/src/main/java/org/crunchytorch/coddy/snippet/api/Snippet.java
> +    public SnippetEntity create(@RequestBody SnippetEntity snippet) {
ok

2018-05-14 11:43 UTC, DavidLevayer commented on back/src/main/java/org/crunchytorch/coddy/user/api/User.java
> +    @PreAuthorize("hasRole('" + Permission.ADMIN + "') or (hasRole('" + Permission.USER + "') and @userSecurityService.ownsAccount(#login))")
D'accord pour la lisibilité. Pas trop convaincu pour le reste... Je te propose qu'on laisse comme ça, on verra à l'usage si le cas que je redoute se produit ;)

2018-05-15 14:10 UTC, Nexucis commented on README.md
> +##### CODDY_SECURITY_JWT_SESSION_TIMEOUT_MIN
done

2018-05-15 18:31 UTC, DavidLevayer approved these changes

2018-05-15 18:31 UTC, merged